"""cross_reference_model.py -- pure functions, no PySide6 dependency."""
from models.cross_reference_model import parse_encap_xref, build_xref_index_macro, render_cross_refs_file


class TestParseEncapXref:
    def test_see_form(self):
        assert parse_encap_xref("see{Widgets}") == ("see", "Widgets")

    def test_seealso_form(self):
        assert parse_encap_xref("seealso{Widgets}") == ("seealso", "Widgets")

    def test_non_xref_encap_returns_none(self):
        assert parse_encap_xref("standard") is None

    def test_empty_string_returns_none(self):
        assert parse_encap_xref("") is None

    def test_none_returns_none(self):
        assert parse_encap_xref(None) is None

    def test_strips_surrounding_whitespace(self):
        assert parse_encap_xref("  see{Widgets}  ") == ("see", "Widgets")

    def test_target_containing_braces(self):
        assert parse_encap_xref("see{A{B}C}") == ("see", "A{B}C")

    def test_malformed_missing_closing_brace_returns_none(self):
        assert parse_encap_xref("see{Widgets") is None


class TestBuildXrefIndexMacro:
    def test_default_command_name(self):
        assert build_xref_index_macro("Gadgets", "see", "Widgets") == r"\index{Gadgets|see{Widgets}}"

    def test_seealso_type(self):
        assert build_xref_index_macro("Gadgets", "seealso", "Widgets") == r"\index{Gadgets|seealso{Widgets}}"

    def test_custom_command_name(self):
        assert build_xref_index_macro("Gadgets", "see", "Widgets", command_name="isidx") == r"\isidx{Gadgets|see{Widgets}}"


class TestRenderCrossRefsFile:
    def test_empty_list_produces_only_the_header(self):
        result = render_cross_refs_file([])
        assert result.startswith("% This file is automatically generated")
        assert r"\index" not in result

    def test_single_row(self):
        result = render_cross_refs_file([{"source_heading": "Gadgets", "xref_type": "see", "target_heading": "Widgets"}])
        assert r"\index{Gadgets|see{Widgets}}" in result

    def test_sorted_case_insensitively_by_source_then_target(self):
        rows = [
            {"source_heading": "zeta", "xref_type": "see", "target_heading": "a"},
            {"source_heading": "Apple", "xref_type": "see", "target_heading": "b"},
        ]
        result = render_cross_refs_file(rows)
        apple_pos = result.index("Apple")
        zeta_pos = result.index("zeta")
        assert apple_pos < zeta_pos

    def test_sort_is_by_source_first_then_target(self):
        rows = [
            {"source_heading": "Same", "xref_type": "see", "target_heading": "zeta"},
            {"source_heading": "Same", "xref_type": "see", "target_heading": "apple"},
        ]
        result = render_cross_refs_file(rows)
        apple_pos = result.index("apple")
        zeta_pos = result.index("zeta")
        assert apple_pos < zeta_pos

    def test_missing_keys_default_gracefully(self):
        result = render_cross_refs_file([{}])
        assert r"\index{|see{}}" in result

    def test_output_ends_with_trailing_newline_when_non_empty(self):
        result = render_cross_refs_file([{"source_heading": "A", "xref_type": "see", "target_heading": "B"}])
        assert result.endswith("\n")
