import re

_ENCAP_XREF_PATTERN = re.compile(r'^(see|seealso)\{(.*)\}$', re.DOTALL)

_GENERATED_FILE_HEADER = (
    "% This file is automatically generated and managed by LaTeX Indexing Editor.\n"
    "% Do not edit by hand -- changes will be overwritten the next time a\n"
    "% cross-reference is added, edited, or removed via the \"Cross-References\"\n"
    "% tab in Edit Entries.\n"
)


def parse_encap_xref(encap: str) -> tuple[str, str] | None:
    """
    Parses a project_references.encap value of the form "see{Target}" or
    "seealso{Target}" into (xref_type, target). Returns None if encap isn't
    a see/seealso pipe-modifier.
    """
    if not encap:
        return None
    match = _ENCAP_XREF_PATTERN.match(encap.strip())
    if not match:
        return None
    return match.group(1), match.group(2)


def build_xref_index_macro(source_raw: str, xref_type: str, target: str, command_name: str = "index") -> str:
    """Builds a standalone `\\index{source|see{target}}`-shaped macro line."""
    return f"\\{command_name}{{{source_raw}|{xref_type}{{{target}}}}}"


def render_cross_refs_file(xrefs: list[dict]) -> str:
    """
    Renders the full contents of cross_refs.tex from a list of
    {"source_heading", "xref_type", "target_heading"} rows (the shape
    FileTreePersistence.fetch_project_cross_references returns). Sorted by
    (source, target) case-insensitively for a deterministic diff between
    regenerations.
    """
    sorted_rows = sorted(
        xrefs,
        key=lambda row: (
            str(row.get("source_heading", "")).lower(),
            str(row.get("target_heading", "")).lower(),
        ),
    )
    lines = [
        build_xref_index_macro(
            row.get("source_heading", ""),
            row.get("xref_type", "see"),
            row.get("target_heading", ""),
        )
        for row in sorted_rows
    ]
    return _GENERATED_FILE_HEADER + "\n".join(lines) + ("\n" if lines else "")
