from models import index_tag_grammar as grammar
from models.latex_dialect import LATEX_DIALECT as dialect

_GENERATED_FILE_HEADER = (
    "% This file is automatically generated and managed by LaTeX Indexing Editor.\n"
    "% Do not edit by hand -- changes will be overwritten the next time a\n"
    "% cross-reference is added, edited, or removed via the \"Cross-References\"\n"
    "% tab in Edit Entries.\n"
)


def parse_encap_xref(encap: str) -> tuple[str, str] | None:
    """
    Parses a project_references.encap value of the form "see{Target}" or
    "seealso{Target}" into (xref_type, target). Returns None if encap isn't
    a see/seealso pipe-modifier.

    Kept as a tuple-returning wrapper over index_tag_grammar because the
    callers here destructure the pair; new code should use
    dialect.parse_xref directly and read .kind/.target.
    """
    spec = dialect.parse_xref(encap)
    return (spec.kind, spec.target) if spec else None


def build_xref_index_macro(source_raw: str, xref_type: str, target: str, command_name: str = "index") -> str:
    """Builds a standalone `\\index{source|see{target}}`-shaped macro line."""
    return grammar.build_xref_macro(source_raw, xref_type, target, command_name)


def render_cross_refs_file(xrefs: list[dict]) -> str:
    """
    Renders the full contents of cross_refs.tex from a list of
    {"source_heading", "xref_type", "target_heading"} rows (the shape
    FileTreePersistence.fetch_project_cross_references returns). Sorted by
    (source, target) case-insensitively for a deterministic diff between
    regenerations.
    """
    sorted_rows = sorted(
        xrefs,
        key=lambda row: (
            str(row.get("source_heading", "")).lower(),
            str(row.get("target_heading", "")).lower(),
        ),
    )
    lines = [
        build_xref_index_macro(
            row.get("source_heading", ""),
            row.get("xref_type", "see"),
            row.get("target_heading", ""),
        )
        for row in sorted_rows
    ]
    return _GENERATED_FILE_HEADER + "\n".join(lines) + ("\n" if lines else "")
