r"""
T3b -- a Table of Authorities as a second named index in a LaTeX manuscript.

**The other half of T3a, and it inverts one thing completely.** A set of page
proofs *observes* its page numbers, so T3a computes locators and writes the
finished table to a file. A LaTeX manuscript has no page numbers at all until
the engine has run --
:meth:`~bookindexcore.backend.base.DocumentBackend.resolve_page_numbers`
returns None for exactly that reason -- so nothing here computes a locator.
What it writes is an ``\index`` macro *at the citation*, and the page number
comes from where that macro lands on the page. The table is generated by
``makeindex``, not by us.

That is what makes this the harder of the two and the reason §8.17 said to do
the standalone path first: here a wrong offset is not a wrong page in a report
we produced, it is a macro inserted into the middle of somebody's sentence.

#### Four things this has to get right

**The text.** A ``.tex`` file is not prose, and the grammar reads prose. See
:mod:`models.latex_text_projection` for the measurement -- every case citation
in a marked-up fixture parsed as a *short form* with a mangled party until the
markup was blanked out.

**The paragraph.** Citations are parsed one paragraph at a time. A party name
never spans a blank line, and the leftward party walk looks back 260
characters, so without this it walks out of the paragraph and into whatever
precedes -- which for the first citation in a chapter is the chapter title. It
produced `Testamentary Capacity Banks v Goodfellow` in the fixture, and it is a
fault this module introduced by blanking rather than one it inherited.

**The sort key.** ``2 U.S.C.`` must file before ``42 U.S.C.``, and ``makeindex``
files alphabetically on the string it is given. T2's filing key is what makes
the order right, so it is emitted as the ``sort@display`` key E4 measured LaTeX
as supporting per level. Without it a table of authorities in code order is not
achievable in this host at all.

**The category.** One named index per category, so each section gets a real
heading from ``imakeidx``'s own ``title=``. The alternative -- one index with
the category as a level -- is `ClassEmulation.NESTED_LEVEL`, which E9 models
and which works, but it spends a level and OSCOLA's Act-and-provision nesting
then needs all three LaTeX allows.

#### Nothing here writes to a file

A :class:`ToaPlan` is a description: where each macro goes, what it says, and
what the preamble needs. Applying it is the controller's, through the ordinary
edit machinery, so it lands in undo and is saved like any other change. That
split is what lets the whole of this be tested without a project open.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Optional, Sequence

from bookindexcore.authorities import (
    CATEGORY_CASE,
    CATEGORY_CONSTITUTIONAL,
    CATEGORY_LABELS,
    CATEGORY_REGULATION,
    CATEGORY_RULE,
    CATEGORY_SECONDARY,
    CATEGORY_STATUTE,
    CitationParser,
    assemble,
    merge_citations,
)
from bookindexcore.sorting import SortRules

from .index_tag_grammar import escape_for_makeindex
from .latex_text_projection import project

__all__ = [
    "INDEX_NAMES",
    "ToaEntry",
    "ToaPlan",
    "build_plan",
    "index_name_for",
    "preamble_for",
]

#: The ``imakeidx`` index name for each category. Short, lower-case and
#: alphanumeric because that is what a ``\makeindex[name=]`` accepts, and
#: prefixed so that a project's own indexes cannot collide with these.
INDEX_NAMES = {
    CATEGORY_CASE: "toacases",
    CATEGORY_STATUTE: "toastatutes",
    CATEGORY_REGULATION: "toaregulations",
    CATEGORY_RULE: "toarules",
    CATEGORY_CONSTITUTIONAL: "toaconstitutional",
    CATEGORY_SECONDARY: "toasecondary",
}

#: A blank line, which is a paragraph break in LaTeX and a boundary no citation
#: crosses. See the module docstring.
_PARAGRAPH = re.compile(r"\n[ \t]*\n")


def index_name_for(category: str) -> Optional[str]:
    return INDEX_NAMES.get(category)


@dataclass(frozen=True)
class ToaEntry:
    """One ``\\index`` macro, and where it goes."""

    container: str
    #: Source offset to insert at -- the end of the citation, so the macro
    #: follows the text it is about and takes that text's page.
    offset: int
    macro: str
    #: What it is about, for a preview surface.
    display: str
    category: str


@dataclass(frozen=True)
class ToaPlan:
    """
    Everything that would be written, and nothing written yet.

    ``entries`` is in **descending offset order within each container**, which
    is not a presentation choice: applying insertions from the end backwards
    means every offset still to be used is unaffected by the ones already
    applied. The alternative is to re-derive coordinates after each insert,
    which this project has already paid for once.
    """

    entries: tuple[ToaEntry, ...]
    preamble: tuple[str, ...]
    table: object
    #: Short forms and unrecognised abbreviations, carried for the surface.
    unresolved: tuple = ()
    unknown: tuple = ()

    @property
    def is_empty(self) -> bool:
        return not self.entries


def preamble_for(table, *, in_toc: bool = True) -> tuple[str, ...]:
    r"""
    The ``\makeindex`` declarations and the ``\printindex`` calls.

    Only for the categories the book actually cites. A ``\makeindex`` for an
    empty index produces a heading with nothing under it, which tells a reader
    the book cites regulations when it does not -- the same rule
    :mod:`~bookindexcore.authorities.assemble` follows for its sections.
    """
    declarations = []
    prints = []
    for section in table.sections:
        name = index_name_for(section.category)
        if name is None:
            continue
        title = CATEGORY_LABELS[section.category]
        options = f"name={name},title={{{title}}}"
        if in_toc:
            options += ",intoc"
        declarations.append(f"\\makeindex[{options}]")
        prints.append(f"\\printindex[{name}]")
    return tuple(declarations), tuple(prints)


def _paragraphs(text: str):
    """``(base_offset, paragraph_text)`` for each paragraph."""
    start = 0
    for match in _PARAGRAPH.finditer(text):
        yield start, text[start:match.start()]
        start = match.end()
    yield start, text[start:]


def _citations_in(container: str, text: str, parser):
    """
    Every citation in one container, at that container's own offsets.

    Parsed a paragraph at a time -- see the module docstring for the chapter
    title this stops the party walk reaching into.
    """
    found = []
    projected = project(text)
    for base, paragraph in _paragraphs(projected):
        if not paragraph.strip():
            continue
        for citation in parser.parse(paragraph):
            found.append((container, base + citation.start,
                          base + citation.end, citation))
    return found


def _join(parts) -> str:
    """
    A key tuple as one string, as ``makeindex`` will compare it.

    T2's key is a tuple, because no separator sorts before every character a
    component can hold. ``makeindex`` wants a string, so the parts are joined
    with a space -- which is safe *here* in a way it is not in general: every
    part is already a filing key, so it carries no separator of its own.

    Empty components are dropped rather than joined. A code with no section
    yields a trailing one, and `mental capacity act 2005 ` sorts before
    `mental capacity act 2005a` for a reason no reader would ever guess at.
    """
    return " ".join(part for part in parts if part)


def _leaf_paths(table):
    r"""
    ``id(authority) -> (category, [(sort, display), ...])``.

    One pair for a flat entry and two for a provision nested under its Act,
    which is the shape ``sort@display!sort@display`` expects.

    **The two levels get different halves of the key**, and that is the part
    worth reading twice. A provision's filing key is the *whole* key -- Act
    name, year, and section -- because T2 files provisions among all the other
    statutes. Emitting that at both levels works, since sections of one Act
    differ in the last component, but it produces

        wills act 1837 9@Wills Act 1837!wills act 1837 9@s 9

    where the second key is mostly a copy of the first. So the Act takes the
    key without its section and the provision takes the section alone: each
    level is sorted by the thing that distinguishes it at that level, which is
    what a per-level sort key is for.
    """
    paths = {}
    for section in table.sections:
        for entry in section.entries:
            nested = bool(entry.subentries)
            # The Act's own key, less the section that belongs to its children.
            head_key = _join(entry.key[:-1] if nested else entry.key)
            head = (head_key, entry.display)
            if entry.authority is not None:
                paths[id(entry.authority)] = (section.category, [head])
            for sub in entry.subentries:
                if sub.authority is not None:
                    paths[id(sub.authority)] = (
                        section.category,
                        [head, (_join(sub.key[-1:]), sub.display)])
    return paths


#: The LaTeX specials that can survive into a citation's display text. Braces
#: and the backslash are absent deliberately: the projection blanks them, so a
#: *parsed* field cannot contain one.
_LATEX_SPECIALS = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
}


def _latex_safe(text: str) -> str:
    r"""
    Escape what LaTeX reads as grammar.

    **Not the same job as escaping for makeindex, and neither one covers the
    other.** `escape_for_makeindex` quotes `!`, `@`, `|` and `"`, which are
    *makeindex's* grammar; `&` is not among them, correctly, because makeindex
    does not care about it. LaTeX does: `\index[t]{Bell & Howell}` fails the
    compile with *"Misplaced alignment tab character &"*, which is a broken
    build rather than a mis-sorted entry, and it was reaching this far because
    the two escapings look like the same thing.

    Applied **before** the makeindex pass, which then leaves the backslash
    sequences alone -- it is documented as passing them through, since `\"` is
    a literal quote to makeindex and doubling it would print ø where ö was
    meant.
    """
    return "".join(_LATEX_SPECIALS.get(char, char) for char in (text or ""))


def _escaped(text: str) -> str:
    return escape_for_makeindex(_latex_safe(text))


def _macro(name: str, path: Sequence[tuple]) -> str:
    r"""
    ``\index[toacases]{sort@display}``, escaped for LaTeX and for makeindex.

    Both halves are escaped. The display half obviously must be -- a case name
    contains ``&`` often enough -- and the **sort half must be too**: a filing
    key is built from the citation's own text, so a key for `Bell & Howell`
    carries the ampersand into a position where an unescaped one breaks the
    build rather than mis-sorting an entry.
    """
    levels = "!".join(
        f"{_escaped(sort)}@{_escaped(display)}" for sort, display in path
    )
    return f"\\index[{name}]{{{levels}}}"


def build_plan(backend, system, rules: SortRules, *,
               in_toc: bool = True) -> ToaPlan:
    """
    Read a manuscript, find its authorities, and describe the entries to write.

    ``backend`` is the application's
    :class:`~bookindexcore.backend.base.DocumentBackend`; only its read half is
    used, which is the same subset §8.17 identified when it argued that a
    paginated source is not a backend.
    """
    parser = CitationParser(system)
    found = []
    for container in backend.containers():
        found.extend(_citations_in(container, backend.read_text(container),
                                   parser))

    # Merging has to cross containers -- an authority cited in chapter 2 and
    # chapter 9 is one entry -- while a Citation carries an offset and no
    # container. Each container gets a base in one global space, exactly as
    # `authorities.paginated.build_table` does, and the map back is kept here.
    import dataclasses

    shifted = []
    origin = {}
    base = 0
    for container, start, end, citation in found:
        moved = dataclasses.replace(citation, start=base, end=base + (end - start))
        origin[base] = (container, end)
        shifted.append(moved)
        base += (end - start) + 1

    merged = merge_citations(shifted, system=system)
    table = assemble(shifted, system, rules, merged=merged)
    paths = _leaf_paths(table)

    entries = []
    for authority in merged.authorities:
        placed = paths.get(id(authority))
        if placed is None:
            continue
        category, path = placed
        name = index_name_for(category)
        if name is None:
            continue
        macro = _macro(name, path)
        for occurrence in authority.occurrences:
            container, at = origin[occurrence.start]
            entries.append(ToaEntry(
                container=container, offset=at, macro=macro,
                display=path[-1][1], category=category))

    # Descending within each container: see `ToaPlan.entries`.
    entries.sort(key=lambda e: (e.container, -e.offset))

    declarations, prints = preamble_for(table, in_toc=in_toc)
    return ToaPlan(
        entries=tuple(entries),
        preamble=declarations + prints,
        table=table,
        unresolved=merged.unresolved,
        unknown=merged.unknown,
    )
